env:

  contexts :

    - name: admin
      urls:
        - 'https://ec-cube/admin'
      includePaths:
        - '\Qhttps://ec-cube/admin\E.*'
      excludePaths:
      authentication:
        method: 'form'
        parameters:
          loginPageUrl: https://ec-cube/admin/login
          loginRequestUrl: https://ec-cube/admin/login
          loginRequestBody: _csrf_token=xxx&login_id={%username%}&password={%password%}
        verification:
          method: 'poll'
          loggedOutRegex: '\Q<button type="submit" class="btn btn-primary btn-lg btn-block">ログイン</button>\E'
          pollFrequency: 1000
          pollUnits: 'requests'
          pollUrl: 'https://ec-cube/admin/login'
      users:
      - name: admin
        credentials:
          username: admin
          password: password

    - name: default
      urls:
        - https://ec-cube
        - http://mailcatcher:1080

  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true

jobs:

  - type: script
    parameters:
      action: add
      type: standalone
      name: configure_tech
      file: /zap/wrk/scripts/configure_tech.js

  - type: script
    parameters:
      action: run
      type: standalone
      name: configure_tech

#  - type: script
#    parameters:
#      action: add
#      type: sequence
#      name: before_script
#      file: /zap/wrk/scripts/__BEFORE_SCRIPT__
#  - type: script
#    parameters:
#      action: run
#      type: sequence
#      name: before_script

  - type: script
    parameters:
      action: add
      type: sequence
      name: target
      file: /zap/wrk/scripts/__TARGET__.zst

  - type: sequence
    parameters:
      action: activeScan
      name: target
      user: __USER__
      context: __CONTEXT__
      threadPerHost: __THREAD_PER_HOST__

  - type: passiveScan-wait

  - type: report
    parameters:
      reportDir: /tmp/report
      reportFile: ZAP-Report-__TARGET__
      reportTitle: __TARGET__

  - type: script
    parameters:
      action: add
      type: standalone
      name: dump_alerts
      file: /zap/wrk/scripts/dump_alerts.js

  - type: script
    parameters:
      action: run
      type: standalone
      name: dump_alerts

  - type: script
    parameters:
      action: add
      type: standalone
      name: assert_no_high_risks
      file: /zap/wrk/scripts/assert_no_high_risks.js

  - type: script
    parameters:
      action: run
      type: standalone
      name: assert_no_high_risks
    tests:
      - name: 'High risk alert count'
        type: stats
        statistic: stats.scan.high.alerts
        operator: '=='
        value: 0
        onFail: 'error'
